-------------------------------------------------------------------------------
Test set: io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest
-------------------------------------------------------------------------------
Tests run: 12, Failures: 0, Errors: 12, Skipped: 0, Time elapsed: 0.528 sec <<< FAILURE! - in io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest
testAddAndGetClusterNodeInfo(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.45 sec  <<< ERROR!
java.lang.NullPointerException: null
	at io.vertx.core.shareddata.AsyncMultiMapTest.setUp(AsyncMultiMapTest.java:37)
	at io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest.setUp(ConsulAsyncBaseMultiMapTest.java:41)

testAddAndGetClusterNodeInfo(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.451 sec  <<< ERROR!
java.lang.IllegalStateException: Assert or failure from non main thread but no await() on main thread
	at io.vertx.test.core.AsyncTestBase.afterAsyncTestBase(AsyncTestBase.java:161)
	at io.vertx.test.core.AsyncTestBase.tearDown(AsyncTestBase.java:71)
	at io.vertx.test.core.VertxTestBase.tearDown(VertxTestBase.java:83)
	at io.vertx.test.core.AsyncTestBase.after(AsyncTestBase.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.AssertionError: Failed to start node
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:199)
	at io.vertx.test.core.VertxTestBase.lambda$startNodes$2(VertxTestBase.java:162)
	at io.vertx.test.core.VertxTestBase.lambda$clusteredVertx$1(VertxTestBase.java:129)
	at io.vertx.core.impl.VertxImpl.lambda$null$1(VertxImpl.java:195)
	at io.vertx.core.impl.VertxImpl$1$1.lambda$operationComplete$0(VertxImpl.java:863)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

testRemoveAllForValueClusterNodeInfo(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.NullPointerException: null
	at io.vertx.core.shareddata.AsyncMultiMapTest.setUp(AsyncMultiMapTest.java:37)
	at io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest.setUp(ConsulAsyncBaseMultiMapTest.java:41)

testRemoveAllForValueClusterNodeInfo(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.014 sec  <<< ERROR!
java.lang.IllegalStateException: Assert or failure from non main thread but no await() on main thread
	at io.vertx.test.core.AsyncTestBase.afterAsyncTestBase(AsyncTestBase.java:161)
	at io.vertx.test.core.AsyncTestBase.tearDown(AsyncTestBase.java:71)
	at io.vertx.test.core.VertxTestBase.tearDown(VertxTestBase.java:83)
	at io.vertx.test.core.AsyncTestBase.after(AsyncTestBase.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.AssertionError: Failed to start node
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:199)
	at io.vertx.test.core.VertxTestBase.lambda$startNodes$2(VertxTestBase.java:162)
	at io.vertx.test.core.VertxTestBase.lambda$clusteredVertx$1(VertxTestBase.java:129)
	at io.vertx.core.impl.VertxImpl.lambda$null$1(VertxImpl.java:195)
	at io.vertx.core.impl.VertxImpl$1$1.lambda$operationComplete$0(VertxImpl.java:863)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

testRemoveClusterNodeInfo(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.019 sec  <<< ERROR!
java.lang.NullPointerException: null
	at io.vertx.core.shareddata.AsyncMultiMapTest.setUp(AsyncMultiMapTest.java:37)
	at io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest.setUp(ConsulAsyncBaseMultiMapTest.java:41)

testRemoveClusterNodeInfo(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.019 sec  <<< ERROR!
java.lang.IllegalStateException: Assert or failure from non main thread but no await() on main thread
	at io.vertx.test.core.AsyncTestBase.afterAsyncTestBase(AsyncTestBase.java:161)
	at io.vertx.test.core.AsyncTestBase.tearDown(AsyncTestBase.java:71)
	at io.vertx.test.core.VertxTestBase.tearDown(VertxTestBase.java:83)
	at io.vertx.test.core.AsyncTestBase.after(AsyncTestBase.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.AssertionError: Failed to start node
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:199)
	at io.vertx.test.core.VertxTestBase.lambda$startNodes$2(VertxTestBase.java:162)
	at io.vertx.test.core.VertxTestBase.lambda$clusteredVertx$1(VertxTestBase.java:129)
	at io.vertx.core.impl.VertxImpl.lambda$null$1(VertxImpl.java:195)
	at io.vertx.core.impl.VertxImpl$1$1.lambda$operationComplete$0(VertxImpl.java:863)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

testRemoveAllForValue(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.014 sec  <<< ERROR!
java.lang.NullPointerException: null
	at io.vertx.core.shareddata.AsyncMultiMapTest.setUp(AsyncMultiMapTest.java:37)
	at io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest.setUp(ConsulAsyncBaseMultiMapTest.java:41)

testRemoveAllForValue(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.014 sec  <<< ERROR!
java.lang.IllegalStateException: Assert or failure from non main thread but no await() on main thread
	at io.vertx.test.core.AsyncTestBase.afterAsyncTestBase(AsyncTestBase.java:161)
	at io.vertx.test.core.AsyncTestBase.tearDown(AsyncTestBase.java:71)
	at io.vertx.test.core.VertxTestBase.tearDown(VertxTestBase.java:83)
	at io.vertx.test.core.AsyncTestBase.after(AsyncTestBase.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.AssertionError: Failed to start node
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:199)
	at io.vertx.test.core.VertxTestBase.lambda$startNodes$2(VertxTestBase.java:162)
	at io.vertx.test.core.VertxTestBase.lambda$clusteredVertx$1(VertxTestBase.java:129)
	at io.vertx.core.impl.VertxImpl.lambda$null$1(VertxImpl.java:195)
	at io.vertx.core.impl.VertxImpl$1$1.lambda$operationComplete$0(VertxImpl.java:863)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

testMapAddGet(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.018 sec  <<< ERROR!
java.lang.NullPointerException: null
	at io.vertx.core.shareddata.AsyncMultiMapTest.setUp(AsyncMultiMapTest.java:37)
	at io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest.setUp(ConsulAsyncBaseMultiMapTest.java:41)

testMapAddGet(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.018 sec  <<< ERROR!
java.lang.IllegalStateException: Assert or failure from non main thread but no await() on main thread
	at io.vertx.test.core.AsyncTestBase.afterAsyncTestBase(AsyncTestBase.java:161)
	at io.vertx.test.core.AsyncTestBase.tearDown(AsyncTestBase.java:71)
	at io.vertx.test.core.VertxTestBase.tearDown(VertxTestBase.java:83)
	at io.vertx.test.core.AsyncTestBase.after(AsyncTestBase.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.AssertionError: Failed to start node
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:199)
	at io.vertx.test.core.VertxTestBase.lambda$startNodes$2(VertxTestBase.java:162)
	at io.vertx.test.core.VertxTestBase.lambda$clusteredVertx$1(VertxTestBase.java:129)
	at io.vertx.core.impl.VertxImpl.lambda$null$1(VertxImpl.java:195)
	at io.vertx.core.impl.VertxImpl$1$1.lambda$operationComplete$0(VertxImpl.java:863)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

testMapRemove(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.NullPointerException: null
	at io.vertx.core.shareddata.AsyncMultiMapTest.setUp(AsyncMultiMapTest.java:37)
	at io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest.setUp(ConsulAsyncBaseMultiMapTest.java:41)

testMapRemove(io.vertx.core.shareddata.ConsulAsyncBaseMultiMapTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.IllegalStateException: Assert or failure from non main thread but no await() on main thread
	at io.vertx.test.core.AsyncTestBase.afterAsyncTestBase(AsyncTestBase.java:161)
	at io.vertx.test.core.AsyncTestBase.tearDown(AsyncTestBase.java:71)
	at io.vertx.test.core.VertxTestBase.tearDown(VertxTestBase.java:83)
	at io.vertx.test.core.AsyncTestBase.after(AsyncTestBase.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.AssertionError: Failed to start node
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:199)
	at io.vertx.test.core.VertxTestBase.lambda$startNodes$2(VertxTestBase.java:162)
	at io.vertx.test.core.VertxTestBase.lambda$clusteredVertx$1(VertxTestBase.java:129)
	at io.vertx.core.impl.VertxImpl.lambda$null$1(VertxImpl.java:195)
	at io.vertx.core.impl.VertxImpl$1$1.lambda$operationComplete$0(VertxImpl.java:863)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

